version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./docker-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pricewars
      - POSTGRES_PASSWORD=1337
      - POSTGRES_DB=marketplace
  
  marketplace:
    build: ./pricewars-marketplace
    image: pricewars/marketplace
    ports:
      - "8080:8080"
    # volumes:
    #   - ./pricewars-marketplace:/marketplace
    links:
      - db
      - producer

  producer:
    build: ./pricewars-producer
    image: pricewars/producer
    ports:
      - "3050:3050"
    # volumes:
    #   - ./pricewars-producer:/producer

  merchant1:
    build: ./pricewars-merchant/simple_competition_logic
    image: pricewars/merchant
    ports:
      - "5001:5001"
    # volumes:
    #   - ./pricewars-merchant/simple_competition_logic:/merchant
    links:
      - producer
      - marketplace
    command: python MerchantApp.py --port 5001

  merchant2:
    build: ./pricewars-merchant/simple_competition_logic
    image: pricewars/merchant
    ports:
      - "5002:5002"
    # volumes:
    #   - ./pricewars-merchant/simple_competition_logic:/merchant
    links:
      - producer
      - marketplace
    command: python MerchantApp.py --port 5002

  consumer:
    build: ./pricewars-consumer
    image: pricewars/consumer
    ports:
       - "3000:3000"
    # volumes:
    #   - ./pricewars-consumer:/consumer
    links:
      - marketplace
